name: prueba1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.0.6
  
  # Image Picker
  image_picker: ^0.8.7+4
  
  # UUID for unique identifiers
  uuid: ^3.0.6
  
  # Social authentication packages
  google_sign_in: ^6.0.2
  flutter_facebook_auth: ^6.0.4  # Versión compatible
  
  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.1.0
  
  # Flutter launcher icons (for custom app icon)
  flutter_launcher_icons: ^0.13.1
  
  # Intl for date and number formatting
  intl: ^0.17.0

  # HTTP package for making API requests to PayPal
  http: ^0.13.5

  # WebView for handling PayPal approval URL
  webview_flutter: ^4.2.3
  flutter_paypal: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/google_logo.png
    - lib/assets/facebook_logo.png