// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2cYAo3t3rcMmbSTlW1gVaM9KnEVT8ogM',
    appId: '1:1060831868115:web:767031a1c50c22b09b1026',
    messagingSenderId: '1060831868115',
    projectId: 'flutterqlo',
    authDomain: 'flutterqlo.firebaseapp.com',
    storageBucket: 'flutterqlo.appspot.com',
    measurementId: 'G-HZJTRYQT7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjoRuHw_MsvPy-Ug75DEBwkc0t_9I8Rjo',
    appId: '1:1060831868115:android:a208ffeeb2e6589e9b1026',
    messagingSenderId: '1060831868115',
    projectId: 'flutterqlo',
    storageBucket: 'flutterqlo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvW3Bu8UfdU6ZgRQjtzRf89sl38df1tdU',
    appId: '1:1060831868115:ios:dd1fd20c3b6c69e29b1026',
    messagingSenderId: '1060831868115',
    projectId: 'flutterqlo',
    storageBucket: 'flutterqlo.appspot.com',
    iosBundleId: 'com.nico.prueba1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvW3Bu8UfdU6ZgRQjtzRf89sl38df1tdU',
    appId: '1:1060831868115:ios:dd1fd20c3b6c69e29b1026',
    messagingSenderId: '1060831868115',
    projectId: 'flutterqlo',
    storageBucket: 'flutterqlo.appspot.com',
    iosBundleId: 'com.nico.prueba1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2cYAo3t3rcMmbSTlW1gVaM9KnEVT8ogM',
    appId: '1:1060831868115:web:afd6b75cd9427f829b1026',
    messagingSenderId: '1060831868115',
    projectId: 'flutterqlo',
    authDomain: 'flutterqlo.firebaseapp.com',
    storageBucket: 'flutterqlo.appspot.com',
    measurementId: 'G-RGZSE1PVPS',
  );
}
